config/routes.rb
Rails.application.routes.draw do
  resources :authentications
  get 'home/index'
  root "home#index"
  # post '/users',         to: 'users#create'
  # get '/users/:user_id', to: 'users#show'
  # get '/users',          to: 'users#index'
  post 'api/v1/login',    to: 'sessions#create'
  post '/logout',   to: 'sessions#destroy'
  get '/logged_in', to: 'sessions#is_logged_in?'
  
  # post '/login', to: 'authentication#authenticate'


  namespace :api do 
    namespace :v1 do 
      resources :users, only: [:index, :show, :create, :edit, :update, :destroy ]
      resources :accounts, only: [:index, :show, :create, :edit, :update, :destroy ]
      resources :payments, only: [:index, :show, :create, :edit, :update, :destroy ]
    end
  end


get "*path", to: 'home#index', via: :all
get "up" => "rails/health#show", as: :rails_health_check

 
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  # before_action :set_authentication, only: %i[ show edit update destroy ]

  # # GET /authentications or /authentications.json
  # def index
  #   @authentications = Authentication.all
  # end

  # # GET /authentications/1 or /authentications/1.json
  # def show
  # end

  # # GET /authentications/new
  # def new
  #   @authentication = Authentication.new
  # end

  # # GET /authentications/1/edit
  # def edit
  # end

  # # POST /authentications or /authentications.json
  # def create
  #   @authentication = Authentication.new(authentication_params)

  #   respond_to do |format|
  #     if @authentication.save
  #       format.html { redirect_to authentication_url(@authentication), notice: "Authentication was successfully created." }
  #       format.json { render :show, status: :created, location: @authentication }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @authentication.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /authentications/1 or /authentications/1.json
  # def update
  #   respond_to do |format|
  #     if @authentication.update(authentication_params)
  #       format.html { redirect_to authentication_url(@authentication), notice: "Authentication was successfully updated." }
  #       format.json { render :show, status: :ok, location: @authentication }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @authentication.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /authentications/1 or /authentications/1.json
  # def destroy
  #   @authentication.destroy!

  #   respond_to do |format|
  #     format.html { redirect_to authentications_url, notice: "Authentication was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end
  skip_before_action :authorize_request, :only => :authenticate

  
  def authenticate
    auth_token = AuthenticateUser.new(authentication_params[:email], authentication_params[:password]).call

    render json: { auth_token: auth_token }
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_authentication
    #   @authentication = Authentication.find(params[:id])
    # end

    # Only allow a list of trusted parameters through.
    def authentication_params
      params.fetch(:authentication, {})
    end
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/views/authentications/_authentication.html.erb
<div id="<%= dom_id authentication %>">
</div>

app/views/authentications/_form.html.erb
<%= form_with(model: authentication) do |form| %>
  <% if authentication.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(authentication.errors.count, "error") %> prohibited this authentication from being saved:</h2>

      <ul>
        <% authentication.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/authentications/edit.html.erb
<h1>Editing authentication</h1>

<%= render "form", authentication: @authentication %>

<br>

<div>
  <%= link_to "Show this authentication", @authentication %> |
  <%= link_to "Back to authentications", authentications_path %>
</div>

app/views/authentications/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Authentications</h1>

<div id="authentications">
  <% @authentications.each do |authentication| %>
    <%= render authentication %>
    <p>
      <%= link_to "Show this authentication", authentication %>
    </p>
  <% end %>
</div>

<%= link_to "New authentication", new_authentication_path %>

app/views/authentications/new.html.erb
<h1>New authentication</h1>

<%= render "form", authentication: @authentication %>

<br>

<div>
  <%= link_to "Back to authentications", authentications_path %>
</div>

app/views/authentications/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @authentication %>

<div>
  <%= link_to "Edit this authentication", edit_authentication_path(@authentication) %> |
  <%= link_to "Back to authentications", authentications_path %>

  <%= button_to "Destroy this authentication", @authentication, method: :delete %>
</div>